#!/bin/bash
# shellcheck disable=SC2154
__c_prompt="\\[$(tput setaf 177)\\]${__bold}"
# shellcheck disable=SC2034
prompt_hide_user=""

if [ -x "${PYENV_ROOT}/bin/pyenv" ]; then
    export PATH="${PYENV_ROOT}/bin:${PATH}"
    eval "$("${PYENV_ROOT}/bin/pyenv" init - bash)"
    eval "$("${PYENV_ROOT}/bin/pyenv" virtualenv-init -)"
fi
