#!/bin/sh

set -ex

sleep 0.2

cp -rafv /etc/cups/. /data/cups

mkdir -vp /data/cups/spool
chown -c root:lp /data/cups/spool
chmod -c 0710 /data/cups/spool

mkdir -vp /data/cups/spool/tmp
chown -c root:lp /data/cups/spool/tmp
chmod -c 1770 /data/cups/spool/tmp

exec /usr/sbin/cupsd -f -s /data/cups/cups-files.conf
