#!/bin/sh

set -e

cd "$(dirname "${0}")/homerun/ansible"

export ANSIBLE_NOCOWS=1

if [ ! -d "venv" ]; then
    python3 -m venv venv
    venv/bin/python -m pip install ansible-core passlib
fi

if [ -n "$(echo " ${*} " | grep -e ' -h ' -e ' --help ' || :)" ]; then
    venv/bin/ansible-playbook --help
    exit 0
fi

playbook="${PLAYBOOK-main}"
fqdn="${FQDN-smkent.net}"
env="${ENV-live}"

if [ -z "${fqdn}" ]; then
    echo "FQDN is empty" >&2
    exit 1
fi

case "${1}" in
    hostvars)
        exec venv/bin/ansible -i "inventories/${env}/hosts.yml" -m debug "${2-all}" \
            -e "fqdn=${fqdn}" \
            -a 'msg={{hostvars[inventory_hostname]}}'
        ;;
esac

if [ ! -d "vault/.git" ]; then
    if [ -z "${HOMELAB_VAULT}" ]; then
        echo "Error: Set \$HOMELAB_VAULT to the URL of your vault repository" >&2
        exit 1
    fi
    git clone "${HOMELAB_VAULT}" vault
fi

if [ "$(cat ".requirements.yml.sha256sum" 2>/dev/null || :)" \
        != "$(sha256sum requirements.yml)" ]; then
    (
        set -x
        venv/bin/ansible-galaxy collection install -r requirements.yml
        venv/bin/python -m pip install -r \
            "${HOME}/.ansible/collections/ansible_collections/linode/cloud/requirements.txt"
    )
    sha256sum requirements.yml > ".requirements.yml.sha256sum"
fi

pipe="./fifo"
_rm_pipe() {
    if [ -e "${pipe}" ]; then
        rm -f "${pipe}"
    fi
}

trap _rm_pipe EXIT INT
_rm_pipe
mkfifo "${pipe}"

gpg -d "vault/ansible.asc" > "${pipe}" &
venv/bin/ansible-playbook -i "inventories/${env}/hosts.yml" \
    -e "@${pipe}" \
    -e "fqdn=${fqdn}" \
    "playbooks/${playbook}.yml" \
    "${@}"
