#!/bin/sh

set -e

cd "$(dirname "${0}")"

playbook="create"

case "${1}" in
    create|destroy)
        playbook="${1}"; shift;;
esac

if [ "${playbook}" = "destroy" ] && [ "${ENV-live}" = "live" ]; then
    echo "Not destroying live environment VPS" >&2
    exit 1
fi

PLAYBOOK="linode-${playbook}" exec ./deploy "${@}"
