version: '3.7'

networks:
  default:
    external:
      name: gateway_default
  local:
    external: false

services:
  mediawiki:
    build: build
    networks:
    - default
    - local
    profiles:
    - cloud
    restart: unless-stopped
    volumes:
    - ./build/static:/var/www/html/app-static/
    - ./data/mediawiki/db:/var/www/data
    - ./data/mediawiki/images:/var/www/html/images
    - ./data/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php

  mysql-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
    - MYSQL_ROOT_PASSWORD=wiki
    - MYSQL_USER=wiki
    - MYSQL_PASSWORD=wiki
    - MYSQL_DATABASE=wiki
    networks:
    - local
    profiles:
    - cloud
    restart: unless-stopped
    volumes:
    - ./data/mysql-db:/var/lib/mysql
