- name: Ensure basic apt packages are installed
  ansible.builtin.apt:
    pkg:
    - git
    - gnupg
    - mdadm
    state: present
    update_cache: true
    cache_valid_time: 600
  become: true
  become_user: root
