- name: Retrieve installed packages list
  package_facts:

- name: Remove unneeded exim4-daemon-light package
  apt:
    pkg:
    - exim4-daemon-light
    state: absent
  when: "'exim4-daemon-light' in ansible_facts.packages"

- name: Install apt packages
  apt:
    pkg:
    - curl
    - git
    - gnupg
    - htop
    - libpam-modules
    - make
    - mdadm
    - msmtp
    - msmtp-mta
    - mtools
    - net-tools
    - ntp
    - python3-pip
    - python3-venv
    - rsync
    - s3cmd
    - tmux
    - universal-ctags
    - vim-nox
    update_cache: true
    state: present

- name: Configure msmtp
  copy:
    dest: /etc/msmtprc
    content: |
      account default
      host localhost
      port 587
      from sys@{{ inventory_hostname }}
      aliases /etc/aliases
      tls on
      tls_certcheck off
    mode: 0640
    owner: root
    group: msmtp

- name: Configure mail aliases
  lineinfile:
    dest: /etc/aliases
    regexp: '^#?root:'
    line: 'root: {{ email }}'
    state: present
    create: true
    mode: 0644
