- name: Get domain info
  linode.cloud.domain_info:
    domain: "{{ fqdn }}"
    api_token: "{{ linode_access_token }}"
  check_mode: no

- name: Get instance info
  linode.cloud.instance_info:
    label: "{{ linode_name|d() or host_public|d() or ansible_host }}"
    api_token: "{{ linode_access_token }}"
  check_mode: no
  register: linode_instance

- name: Remove DNS records
  linode.cloud.domain_record:
    domain: "{{ fqdn }}"
    name: "{{ item }}"
    type: A
    target: "{{ linode_instance.networking.ipv4.public.0.address }}"
    api_token: "{{ linode_access_token }}"
    state: absent
  with_items:
  - '{{ "" if host_public|d() == fqdn else inventory_hostname }}'
  - '*{{ "" if host_public|d() == fqdn else "." + inventory_hostname }}'

- name: Destroy instance
  linode.cloud.instance:
    label: "{{ linode_name|d() or host_public|d() or ansible_host }}"
    type: g6-standard-1
    region: us-southeast
    api_token: "{{ linode_access_token }}"
    state: absent
