secrets:
  deploy-backup-ssh-key:
    file: ../../secrets/deploy-backup-ssh-key
  healthchecks-ping-key:
    file: ../../secrets/healthchecks-ping-key
  rclone-s3:
    file: ../../secrets/rclone-s3

services:
  rclone:
    image: ghcr.io/smkent/homelab/hc-task-runner:latest
    # build: ../../images/hc-task-runner
    env_file:
    - host.env
    - rclone.env
    environment:
      SYNC_DEST: /deploy/external
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.sync-external.schedule: "@every 6h"
      ofelia.job-exec.sync-external.command: runitor -create -- /scripts/sync_external
      ofelia.job-exec.sync-external.user: "1000:1000"
    restart: unless-stopped
    secrets:
    - deploy-backup-ssh-key
    - healthchecks-ping-key
    - rclone-s3
    volumes:
    - ../../volumes/${COMPOSE_PROJECT_NAME}/rclone_config:/config/rclone:rw
    - ./scripts:/scripts:ro
    - $HOME/external:/deploy/external:rw
