# Install dotfiles repository
# This repository can't be cloned directly to $HOME, as git requires the clone
# destination to be absent. Instead, clone to a temporary directory, move the
# .git directory to $HOME, and check out the repository contents.

- name: Check if dotfiles repository is installed
  git:
    repo: https://github.com/smkent/dotfiles
    dest: '{{ user_register.home }}'
    clone: false
    update: false
  become_user: '{{ loop_user.user }}'
  when: not ansible_check_mode or not user_register.changed
  register: dotfiles_exists

- name: Install dotfiles repository
  block:
  - name: Clone dotfiles repository
    git:
      repo: https://github.com/smkent/dotfiles
      dest: /tmp/dotfiles_temp

  - name: Move repository metadata directory into place
    command: mv /tmp/dotfiles_temp/.git "{{ user_register.home }}"
    args:
      chdir: '{{ user_register.home }}'
      removes: /tmp/dotfiles_temp/.git
      creates: '{{ user_register.home }}/.git'

  - name: Check out dotfiles repository contents
    git:
      repo: https://github.com/smkent/dotfiles
      dest: '{{ user_register.home }}'
      clone: false
      force: true

  - name: Clean up temporary dotfiles repository directory
    file:
      path: /tmp/dotfiles_temp
      state: absent
    diff: false
    no_log: true
  become_user: '{{ loop_user.user }}'
  when: dotfiles_exists.skipped is not defined and not dotfiles_exists.before
