- name: Install pip packages
  pip:
    name:
    - pipx
    extra_args: --user
    state: present
  become_user: '{{ loop_user.user }}'
  when: not ansible_check_mode

- name: Install pipx packages
  community.general.pipx:
    name: '{{ item }}'
    state: present
  loop:
  - docker-compose
  - poetry
  become_user: '{{ loop_user.user }}'
  when: not ansible_check_mode
