- name: Clone homelab repository
  git:
    repo: https://github.com/smkent/homelab
    dest: '{{ deploy_user_info.home }}/homelab'
    version: main
    accept_hostkey: true
  environment:
    GIT_TERMINAL_PROMPT: 0

- name: Symlink apps
  file:
    src: homelab/apps
    dest: '{{ deploy_user_info.home }}/{{ apps_dir }}'
    owner: '{{ deploy_user }}'
    group: '{{ deploy_user }}'
    state: link
  ignore_errors: '{{ ansible_check_mode }}'

- name: Create deployment directories
  file:
    path: '{{ deploy_user_info.home }}/{{ item.name }}'
    mode: '{{ item.mode }}'
    owner: '{{ item.owner|default(deploy_user) }}'
    group: '{{ item.group|default(deploy_user) }}'
    state: directory
  loop:
  - {name: secrets, mode: '0700'}
  become_user: root
