#!/bin/sh

set -e

SUBMIT_USER="${SUBMIT_USER:-gomail}"

if [ -n "${SUBMIT_USER}" ] \
        && [ -n "${SUBMIT_PASSWORD_FILE}" ] \
        && [ -f "${SUBMIT_PASSWORD_FILE}" ]; then
    saslpasswd2 -c -u "${POSTFIX_myhostname?}" "${SUBMIT_USER}" < "${SUBMIT_PASSWORD_FILE}"
    mkdir -vp /var/spool/postfix/etc
    cp -vf /etc/sasldb2 /var/spool/postfix/etc
fi

if [ -n "${RELAYHOST}" ]; then
    saslpass_file="/etc/saslpass"
    export POSTFIX_relayhost="${RELAYHOST}"
    echo "${RELAYHOST} ${SUBMIT_USER}:$(cat "${SUBMIT_PASSWORD_FILE}")" > "${saslpass_file}"
    chmod -c 400 "${saslpass_file}"
    postmap "${saslpass_file}"
    export POSTFIX_inet_protocols="ipv4"
    export POSTFIX_smtp_use_tls="yes"
    export POSTFIX_smtp_sasl_auth_enable="yes"
    export POSTFIX_smtp_sasl_password_maps="hash:/etc/saslpass"
    export POSTFIX_smtp_tls_security_level="encrypt"
    export POSTFIX_smtp_sasl_security_options="noanonymous"
fi

exec /root/run
