CREATE DATABASE authelia;
CREATE USER authelia WITH PASSWORD 'authelia';
GRANT ALL PRIVILEGES ON DATABASE authelia TO authelia;
REVOKE CONNECT ON DATABASE authelia FROM PUBLIC;
\c authelia
GRANT ALL ON SCHEMA public TO authelia;

CREATE DATABASE lldap;
CREATE USER lldap WITH PASSWORD 'lldap';
GRANT ALL PRIVILEGES ON DATABASE lldap TO lldap;
REVOKE CONNECT ON DATABASE lldap FROM PUBLIC;
\c lldap
GRANT ALL ON SCHEMA public TO lldap;
