#!/bin/sh
set -e

fn="${1?}"
shift
if [ ! -f "${fn}" ]; then
    echo "${fn} does not exist" >&2
    exit 1
fi

set -x
(
    cd "$(readlink -f "$(dirname "$(readlink -f "${0}")")")/.."
    docker-compose exec -T ldap slapadd -F /bitnami/openldap/slapd.d/ "${@}"
) < "${fn}"
