#!/bin/sh
linode_creds_ini=/tmp/certbot-linode.ini

if [ -f "${CERTBOT_LINODE_API_KEY?}" ]; then
    linode_api_key=$(cat "${CERTBOT_LINODE_API_KEY}")
elif [ -f "/run/secrets/${CERTBOT_LINODE_API_KEY?}" ]; then
    linode_api_key=$(cat "/run/secrets/${CERTBOT_LINODE_API_KEY}")
else
    linode_api_key="${CERTBOT_LINODE_API_KEY}"
fi
if [ -z "${linode_api_key}" ]; then
    echo "Error: Linode API key not found via \$CERTBOT_LINODE_API_KEY" >&2
    exit 1
fi

cat >"${linode_creds_ini}" <<EOF
dns_linode_key = ${linode_api_key}
dns_linode_version = ${CERTBOT_LINODE_API_VERSION:-4}
EOF
chmod 400 "${linode_creds_ini}"

certbot_args=
if [ -n "${CERTBOT_EMAIL}" ]; then
    certbot_args="${certbot_args} -m ${CERTBOT_EMAIL}"
fi

cert_for_hosts() {
    certbot_host_args=
    for host in ${1?}; do
        certbot_host_args="${certbot_host_args} -d ${host}"
    done
    shift

    (
        set -x
        # shellcheck disable=SC2086
        certbot \
            certonly \
            -v \
            -n \
            --expand \
            --agree-tos \
            --dns-linode \
            --dns-linode-propagation-seconds "${CERTBOT_LINODE_DNS_SECONDS:-180}" \
            --dns-linode-credentials "${linode_creds_ini}" \
            ${certbot_args} \
            ${certbot_host_args} \
            "${@}"
    )
}

for host_set in "${CERTBOT_HOSTS}" ${CERTBOT_EXTRA_HOSTS-}; do
    cert_for_hosts "${host_set}" "${@}"
done

if [ -n "${CERTBOT_INIT}" ]; then
    exit 0
fi

# Check for renewal once every 12 hours
trap exit TERM
while :; do
    sleep 12h
    certbot renew
done
