#!/bin/sh

set -e

PLUGINS="
    https://github.com/kanboard/plugin-oauth2 OAuth2 v1.0.2
    https://github.com/creecros/MarkdownPlus MarkdownPlus 1.1.0
    https://github.com/kanboard/plugin-gantt Gantt v1.0.6
    https://github.com/BlueTeck/kanboard_plugin_boardcustomizer Boardcustomizer v1.1.0
    https://github.com/kenlog/Moon Moon v1.4.6
    https://github.com/creecros/Customizer Customizer 1.13.8
"

# Correct directory permissions
chown -c nginx:nginx \
    /var/www/app/data \
    /var/www/app/plugins

# Install plugins
apk add git sudo
(
    cd /var/www/app/plugins
    echo "${PLUGINS}" | while read -r repo dest branch; do
        if [ -z "${repo}" ]; then
            continue
        fi
        if [ ! -d "${dest}" ]; then
            (
                set -x
                sudo -u nginx git clone --single-branch "${repo}" "${dest}" -b "${branch}"
            )
        else
            (
                set -x
                cd "${dest}"
                sudo -u nginx git pull
                sudo -u nginx git checkout "${branch}"
            )
        fi
    done
)

exec /usr/local/bin/entrypoint.sh "${@}"
