#!/bin/sh

set -eu

exec 8<>"${TMPDIR-/tmp}/$(basename "${0}")_lock"
flock -n 8 || { echo "Unable to acquire lock"; exit 1; }

docker ps --format='{{.Names}} {{.Image}}' --filter="status=running" \
    | grep 'postgres:' \
    | awk '{print $1}' \
    | while read -r container_name; do
        (
            set -x
            docker exec "${container_name}" \
                sh -c 'pg_dumpall -U "${POSTGRES_USER}" > /var/lib/postgresql/dump.sql'
        )
    done
