#!/bin/sh

set -eu

export RESTIC_REPOSITORY="${1:?First argument must be \"{{ .Repo.Uri \}\}\"}"
export BACKREST_EVENT="${2:?Second argument must be \"{{ .Event \}\}\"}"
export SOURCES="${3:-/backup}"

export RESTIC_PASSWORD_FILE="${RESTIC_PASSWORD_FILE:-/run/secrets/restic-password}"
export RESTIC_FROM_PASSWORD_FILE="${RESTIC_PASSWORD_FILE}"

ensure_repo() {
    [ -d "${1?}" ] && [ -f "${1?}/config" ]
}

case "${RESTIC_REPOSITORY}" in
    /*) ;;  # Local filesystem path
    *) exit 0 ;;
esac

if ! ensure_repo "${RESTIC_REPOSITORY}"; then
    echo "No restic repository found at ${1?}"
    exit 1
fi

mirror_event() {
    src_repo="${1:?}"
    tag_set="${2:?}"
    case "${BACKREST_EVENT}" in
        CONDITION_SNAPSHOT_START)
            (
                set -x
                restic copy --from-repo "${src_repo}" --tag "${tag_set}" latest
            )
            ;;
        CONDITION_FORGET_START)
            (
                set -x
                restic forget \
                    --group-by "" \
                    --tag "${tag_set}" \
                    --prune \
                    --keep-within-monthly 365d \
                    --keep-last 3
            )
            ;;
        *)
            echo "Unsupported event type ${BACKREST_EVENT}" >&2
            return 1
            ;;
    esac
}

find "${SOURCES}" -maxdepth 1 -type d | while read -r src_repo; do
    ensure_repo "${src_repo}" || continue
    restic -r "${src_repo}" snapshots --json \
            | jq -r '.[].tags | select(length > 0) | sort | join(",")' \
            | sort -u \
            | while read -r tag_set; do
        echo ">>> Repository ${src_repo} :: ${tag_set}"
        mirror_event "${src_repo}" "${tag_set}"
    done
done
