- name: Install .local/shell-rc
  template:
    src: shell-rc.j2
    dest: '{{ deploy_user_info.home }}/.local/shell-rc'
    owner: '{{ deploy_user }}'
    group: '{{ deploy_user }}'
    mode: 0755

- name: Install .s3cfg
  template:
    src: s3cfg.j2
    dest: '{{ deploy_user_info.home }}/.s3cfg'
    owner: '{{ deploy_user }}'
    group: '{{ deploy_user }}'
    mode: 0600
  diff: false
