version: '3.7'

networks:
  default:
    external:
      name: gateway_default
  local:
    external: false

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    networks:
    - default
    - local
    restart: unless-stopped
    privileged: true
    profiles:
    - onprem
    volumes:
    - ./data/homeassistant/config:/config
    - /etc/localtime:/etc/localtime:ro
    - /run/dbus:/run/dbus:ro

  esphome:
    image: ghcr.io/esphome/esphome
    env_file:
    - $HOME/secrets/esphome.env
    environment:
    - ESPHOME_DASHBOARD_USE_PING=1
    networks:
    - local
    restart: unless-stopped
    privileged: true
    profiles:
    - onprem
    volumes:
    - ./data/esphome/config:/config
    - /etc/localtime:/etc/localtime:ro

  esphome-oidc:
    image: quay.io/oauth2-proxy/oauth2-proxy
    command: --config=/etc/oauth2-proxy.cfg
    env_file:
    - $HOME/secrets/esphome-oidc.env
    environment:
    - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
    - OAUTH2_PROXY_UPSTREAMS=http://esphome:6052
    - OAUTH2_PROXY_PROVIDER=oidc
    - OAUTH2_PROXY_PROVIDER_DISPLAY_NAME=${HOST_SUFFIX?}
    - OAUTH2_PROXY_REDIRECT_URL=https://esphome.${HOST?}/oauth2/callback
    - OAUTH2_PROXY_OIDC_ISSUER_URL=https://${HOST_SUFFIX?}
    - OAUTH2_PROXY_COOKIE_SECURE=true
    - OAUTH2_PROXY_EMAIL_DOMAINS=*
    networks:
    - default
    - local
    profiles:
    - onprem
    restart: unless-stopped
    volumes:
    - ./oauth2-proxy/oauth2-proxy.cfg:/etc/oauth2-proxy.cfg:ro
