version: '3.7'

networks:
  default:
    external:
      name: gateway_default
  local:
    external: false

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    depends_on:
    - homeassistant-multicast-relay
    - whisper
    - piper
    networks:
    - default
    - local
    restart: unless-stopped
    privileged: true
    profiles:
    - onprem
    volumes:
    - ./data/homeassistant/config:/config
    - /etc/localtime:/etc/localtime:ro
    - /run/dbus:/run/dbus:ro

  homeassistant-multicast-relay:
    image: scyto/multicast-relay:latest
    environment:
    - INTERFACES=eno1 br-f0e63f23efd0 br-1a6eee85d250
    - TZ=UTC
    - OPTS=--verbose
    network_mode: host
    privileged: true

  whisper:
    image: rhasspy/wyoming-whisper
    command: --model base-int8 --language en
    environment:
    - TZ=America/Los_Angeles
    networks:
    - local
    restart: unless-stopped
    volumes:
    - ./data/whisper:/data

  piper:
    image: rhasspy/wyoming-piper
    command: --voice en_GB-southern_english_female-low
    environment:
    - TZ=America/Los_Angeles
    restart: unless-stopped
    volumes:
    - ./data/piper:/data
