- name: Ensure apt keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755
    owner: root
    group: root
  register: apt_keyring_dir

- name: Ensure Tailscale apt GPG key is present
  ansible.builtin.get_url:
    url: "https://pkgs.tailscale.com/stable/{{ ansible_facts['distribution'] | lower }}/{{ ansible_facts['distribution_release'] }}.noarmor.gpg"
    dest: /etc/apt/keyrings/tailscale.gpg
    mode: 0644
  register: apt_tailscale_key
  when:
  - not ansible_check_mode
  - not apt_keyring_dir.changed

- name: Ensure Tailscale apt repository is installed
  ansible.builtin.deb822_repository:
    name: tailscale
    types: deb
    uris: "https://pkgs.tailscale.com/stable/{{ ansible_facts['distribution'] | lower }}"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: /etc/apt/keyrings/tailscale.gpg
    state: present
  register: apt_tailscale_repo
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure Tailscale is installed
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: true
    cache_valid_time: "{{ 0 if apt_tailscale_repo.changed else 600 }}"
  register: apt_tailscale_packages
  failed_when: not ansible_check_mode and apt_tailscale_packages.failed

- name: Ensure tailscaled is enabled and running
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started
  failed_when: not ansible_check_mode and apt_tailscale_packages.failed

- name: Check if Tailscale is authenticated
  ansible.builtin.command:
    cmd: tailscale status
  check_mode: false
  register: tailscale_status
  changed_when: false
  failed_when: false

- name: "Ensure Tailscale operator is set to {{ deploy_user }}"
  ansible.builtin.command:
    argv:
    - tailscale
    - set
    - --operator
    - "{{ deploy_user }}"
  when:
  - tailscale_status.rc != 0
