- name: VPS teardown
  collections:
  - linode.cloud
  hosts: all
  gather_facts: false
  roles:
  - name: linode-destroy
    delegate_to: localhost
    serial: 2
    when: '"onprem" not in group_names'
