- name: Provision homelab host
  collections:
  - community.general
  hosts: all
  roles:
  - users
  - packages
  - system
  - deploy_user
  - {name: apps, become_user: '{{ deploy_user }}', when: deploy_user_info.exists}
  - {name: helmet, when: '"onprem" in group_names'}
  become: true
