#!/bin/sh

set -e

SUBMIT_USER="${SUBMIT_USER:-gomail}"

if [ -n "${SUBMIT_USER}" ] \
        && [ -n "${SUBMIT_PASSWORD_FILE}" ] \
        && [ -f "${SUBMIT_PASSWORD_FILE}" ]; then
    saslpasswd2 -c -u "${POSTFIX_myhostname?}" "${SUBMIT_USER}" < "${SUBMIT_PASSWORD_FILE}"
    mkdir -vp /var/spool/postfix/etc
    cp -vf /etc/sasldb2 /var/spool/postfix/etc
fi

if [ -n "${RELAY_MAP}" ]; then
    while [ -n "${RELAY_MAP}" ]; do
        pair="${RELAY_MAP%%;*}"
        echo "${pair}" | sed -e 's/,/ /'
        RELAY_MAP="${RELAY_MAP#*;}"
        [ "${pair}" = "${RELAY_MAP}" ] && break
    done > /etc/postfix/transport
    postmap /etc/postfix/transport
    export POSTFIX_transport_maps=hash:/etc/postfix/transport
    POSTFIX_relay_domains="$(awk '{print $1}' /etc/postfix/transport | paste -sd, -)"
    export POSTFIX_relay_domains
fi

exec /root/run
