#!/bin/sh

want_rsa_bits=8192

set -ex

if [ "$(ssh-keygen -l -f /etc/ssh/ssh_host_rsa_key | awk '{print $1}')" -lt "${want_rsa_bits?}" ]; then
    printf "%s" "y\n" | ssh-keygen -t rsa -b "${want_rsa_bits?}" -f /etc/ssh/ssh_host_rsa_key -N ''
fi
